package com.lh.repository;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.lh.common.dao.IBaseDao;
import com.lh.po.Admin;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("adminMybatisDao")
public interface IAdminMybatisDao extends IBaseDao<Admin> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    PageList<Admin> fuzzySearchByPager(@Param("item") Admin record, @Param("pageBounds") PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    List<Admin> fuzzySearch(@Param("item") Admin record);
}