package com.lh.repository;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.lh.po.CarBase;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("carbaseMybatisDao")
public interface ICarbaseMybatisDao extends com.lh.common.dao.IBaseDao<CarBase> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbase
     *
     * @mbg.generated
     */
    PageList<CarBase> fuzzySearchByPager(@Param("item") CarBase record, @Param("pageBounds") PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbase
     *
     * @mbg.generated
     */
    List<CarBase> fuzzySearch(@Param("item") CarBase record);
}