package com.lh.repository;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.lh.common.dao.IBaseDao;
import com.lh.po.User;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("userMybatisDao")
public interface IUserMybatisDao extends IBaseDao<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    PageList<User> fuzzySearchByPager(@Param("item") User record, @Param("pageBounds") PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> fuzzySearch(@Param("item") User record);
}